image: python:3.9
pipelines:
  default:
    - step:
        name: Deploy to Lambda
        script:
          - pipe: atlassian/aws-lambda-deploy:1.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: us-east-1
              FUNCTION_NAME: 'stori-take-home-lambda'
              COMMAND: 'update'
              ZIP_FILE: 'dist/stori-take-home.zip'
